### ISSUE TITLE
Outcomes - missing initial cohort entry event

### ISSUE THREAD

**Issue by kmkostka** [ohdsi-studies/MusculosketalAEsAfterAIs#2]
We need to specify an initial Cohort Entry Event. This is what we build our Index Event off of.

Currently, the Os are assembled with additional restrictions and additional inclusion criteria. We need to promote something to the "Cohort Entry Event". I would suggest one of the OA condition occurrence codes.

Here's a cheat sheet of what I mean in screenshot form: https://ohdsi.github.io/TheBookOfOhdsi/Cohorts.html#defining-a-cohort-for-hypertension - check out 10.7.1

**Comment by jennifercelane** [comment]
apologies! hopefully these are now made better. outstanding is to also adapt the cohort definitions for the outcomes anatomical subgroups
